### PR TITLE
Added support for -subdomain and -authtoken

### PR DESCRIPTION
**Pull request by sam-albon-li**
Added support for `-subdomain` and `-authtoken` in the same way previous arguments had been added.

### CODE REVIEW

**Comment by mattbsea** [comment]
👍 -  Came here looking for Auth token support.  Using `lugana707/ngrok:latest` with AUTH_TOKEN environment variable.  Works great!  Thanks!

**Comment by bkrnetic** [comment]
I've tried running the following command: 

```
docker run --rm -it --link <container_name> --net <network_name> --env AUTH_TOKEN=<auth_token> lugana707/ngrok:latest ngrok http <container_name>:80
```

and it links it properly, but I still don't get redirected. Instead of being redirected all I get is the screen where it says:

> Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken.Make sure that you Install Your Authtoken and then restart the ngrok agent.

Ngrok support noted that in an effort to curb abuse, they now require anyone serving HTML content to have an account and use an authtoken.

And it's happening only recently. I've used `shkoliar/ngrok` normally only 2 weeks ago.

Am I doing something wrong?

**Comment by bkrnetic** [comment]
I've managed to find a workaround, these are the steps:

- Create `ngrok.yml` file and paste the following content:
```
web_addr: 0.0.0.0:4551
authtoken: <your_auth_token>
```
- navigate to directory where you created the file and run the command:
```
docker run --rm -it --link <container_name> --net web -v $PWD/ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml shkoliar/ngrok ngrok http <container_name>:80
```

What we did is we mounted our configuration file to the container.

You can replace `$PWD` part of the command depending on your OS. I'm using macOS Big Sur.

I'm still interested to see the solution with token passed directly via command.

**Comment by shkoliar** [comment]
Hi @bkrnetic,

I've updated the docker image and added some corrections, you could try:

```bash
docker pull shkoliar/ngrok
docker run --rm -it --link <container_name> --net web --env AUTH_TOKEN=<auth_token> shkoliar/ngrok http <container_name>:80
```

cc @Lugana707 @mattbsea

**Comment by bkrnetic** [comment]
Tested it and it works perfectly! Thanks a lot Dmitry!

**Pull request merged**
